[package]
name = "sys"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
regex = "1.11.1"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
sysinfo = "0.32.0"
mysql="*"
